name: PR Buid/Test

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ main ]

jobs:
  
  check-build-test:

    runs-on: macos-12

    steps:

    - name: Install Tools
      run: |
        brew install xcbeautify
      env:
        HOMEBREW_NO_INSTALL_CLEANUP: 1

    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_14.1.app/Contents/Developer

    - name: SwiftLint
      run: |
        mkdir .build
        swiftlint lint --reporter json > .build/swiftlint.json

    - name: Build/Test
      run: set -o pipefail && swift test --enable-code-coverage --sanitize undefined | xcbeautify

    - name: Convert Coverage
      run: xcrun llvm-cov show -instr-profile=.build/debug/codecov/default.profdata .build/debug/ShieldPackageTests.xctest/Contents/MacOS/ShieldPackageTests > .build/coverage.report

    - name: Save PR Number
      run: echo ${{ github.event.number }} > .build/pr_number

    - name: Upload Build Results
      uses: actions/upload-artifact@v3
      with:
        name: build-results
        # "./dummy" is included to ensure ".build" path is archived
        path: |
          ./dummy
          .build/pr_number
          .build/swiftlint.json
          .build/coverage.report
          .build/test-results.xml

  build-test:

    permissions:
      checks: write

    runs-on: macos-12

    needs: [check-build-test]

    strategy:
      matrix:
        platform: [macos]

    steps:

    - name: Install Tools
      run: |
        brew tap a7ex/homebrew-formulae
        brew install xcbeautify findsimulator
      env:
        HOMEBREW_NO_INSTALL_CLEANUP: 1
      
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_14.1.app/Contents/Developer

    - name: Build/Test
      run: make build-test-${{ matrix.platform }}

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results-${{ matrix.platform }}
        # "./dummy" is included to ensure "TestResults" path is archived
        path: |
          ./dummy
          TestResults/*.xcresult/
